VlForInstaBan: 1000
VlForBanwave: 500
BanwaveRate: 6000 #In ticks
Minimum: 20 #Minimum VL to warn staff members
SecondsMinimum: 5000 #Delay between warning messages of the same color
DevMode: false
Global: true #Whether or not all checks are enabled
VlColors:
- '&a'
- '&e'
- '&6'
- '&c'
- '&4'
LagBack: false
Log: true
CommandsForBan:
- ban %player% Hacking (%hack%)
- say %player% was banned for %hack%
CommandsForBanwave:
- ban %player% Hacking - Banwave (%hack%)
- say %player% was banwaved for %hack%