VlForInstaBan: 1000
VlForBanwave: 500
BanwaveRate: 6000
Minimum: 20
SecondsMinimum: 5000
DevMode: false
Global: true
VlColors:
- '&a'
- '&e'
- '&6'
- '&c'
- '&4'
LagBack: false
Log: true
CommandsForBan:
- kick %player% Hacking (%hack%)|%token%
- say %player% was banned for %hack% (%token%)
CommandsForBanwave:
- kick %player% Hacking - Banwave (%hack%)|%token%)
- say %player% was banwaved for %hack% (%token%)
UploadLogToPastebin: true