# ----------------------------------------------------------
#
#               NOPE Anti-Cheat Configuration
#
#   This is the configuration for NOPE. I recommend keeping
#    the default values unless you know what you're doing.
#
# ----------------------------------------------------------
ConfigVersion: 1.3.3
#               -------------------------------
#                     Global Configuration
#               -------------------------------

Global: true # If disabled, NOPE will be disabled
# Whether or not to teleport the player back when they're flagged
SetBack: false 
Scoreboard: true
# NONE, file, or hastebin
# hastebin will not work if dev mode is enabled to prevent abuse
# hastebin will log the link to the log within the file
Log: file # NONE, file, or hastebin
UpdateChecker:
  Enabled: true
  InGame: true
BungeeNameOverride: '' # If not empty this will override the server name

#               -------------------------------
#                     Banwave Configuration
#               -------------------------------

VlForInstaBan: 1200 # Minimum VL required for instant ban
VlForBanwave: 800 # Minimum VL required to be queued for banwave
BanwaveRate: 36000 # Rate of banwave (in ticks) -1 to disable

#               -------------------------------
#                  Notification Configuration
#       Make sure staff members have nope.message.normal
#               -------------------------------

Minimum: 30 #Minimum VL to notify staff members
SecondsMinimum: 10000 #Cooldown of hack messages to prevent spam

# Each new color is a new level, this is based off percentage to VL for instant ban
# More colors = more notifications
VlColors: 
- '&a'
- '&6'
- '&4'

# If enabled, developer messages will be sent to the player and commands will not execute
DevMode: false 
DebugMode: false

#               -------------------------------
#                  Punishment Configuration
#      Here you can configure how long punishments are for.
#          NOPE will automatically use a ban manager
#               if one is on the server. This
#            duration will be reflected on the bans.
#                Durations are in milliseconds
#               -------------------------------
UseBanManager: true

BanDurations:
  AutoClicker: -1 # Permanent
  Flight: 7.884e+9 # 3 Months
  KillAura: 5.256e+9 # 2 Months
  Jesus: 2.628e+9 + # 1 Month
  Default: 2.628e+9 # 1 Month


# Placeholders:

# %player% - The name of the player that was banned
# %hack% - What hack the player was banned for
# %vl% - The VL of the hack that the player was at when they were banned
# %world% - What world the player was in when they were banned, this may be null if they were offline
# %token% - The ban token
# %timing% - Can be Banwave or Instant
# PAPI is also supported

TempBanFormat:
- '&4&l[&c&lNOPE Anti-Cheat&4&l]'
- '&7Hacking has been detected on your Minecraft Client.'
- '&7As such, you have been &ctemporarily banned&7 for &e%duration%&7.'
- ''
- '&7Hack Detected: &4%hack% &c(&6%vl%&c)'
- ''
- '&7If you believe you were incorrectly banned,'
- 'Please include the following token when appealing.'
- '&e%token%'

PermBanFormat:
- '&4&l[&c&lNOPE Anti-Cheat&4&l]'
- '&7Hacking has been detected on your Minecraft Client.'
- '&7As such, you have been &cpermanently banned&7.'
- ''
- '&7Hack Detected: &4%hack% &c(&6%vl%&c)'
- ''
- '&7If you believe you were incorrectly banned,'
- 'Please include the following token when appealing.'
- '&e%token%'

CommandsForBan:
- say %name% was banned for %hack% (%token%)

CommandsForBanwave:
- say %name% was banned for %hack% (%token%)


#               -------------------------------
#                     Check Configuration
#       Here you can configure which checks are/aren't enabled
#         You can also toggle these ingame with /nope stats
#   make sure to restart your server after modifying these settings
#               -------------------------------

Checks:
  Movement:
    Enabled: true
    Flight:
      Enabled: true
      Flight#4:
        Enabled: true
      Flight#6:
        Enabled: true
      Flight#1:
        Enabled: true
      Flight#5:
        Enabled: true
      Flight#2:
        Enabled: true
      Flight#3:
        Enabled: true
    NoSlowDown:
      Enabled: true
      NoSlowDown#1:
        Enabled: true
      NoSlowDown#5:
        Enabled: true
      NoSlowDown#4:
        Enabled: true
      NoSlowDown#2:
        Enabled: true
      NoSlowDown#3:
        Enabled: true
    Glide:
      Enabled: true
      Glide#1:
        Enabled: true
    GlobalSprint:
      Enabled: true
      GlobalSprint#1:
        Enabled: true
    BHop:
      Enabled: true
      BHop#1:
        Enabled: true
    Speed:
      Enabled: true
      Speed#1:
        Enabled: true
      Speed#4:
        Enabled: true
      Speed#3:
        Enabled: true
      Speed#2:
        Enabled: true
    InventoryMove:
      Enabled: true
      InventoryMove#1:
        Enabled: true
    Spider:
      Enabled: true
      Spider#1:
        Enabled: true
    ClonedMovements:
      Enabled: true
      ClonedMovement#1:
        Enabled: true
    AntiAFK:
      Enabled: true
      AntiAFK#1:
        Enabled: true
    AutoWalk:
      Enabled: true
      AutoWalk#1:
        Enabled: true
    Jesus:
      Enabled: true
      Jesus#2:
        Enabled: true
      Jesus#1:
        Enabled: true
    NoWeb:
      Enabled: true
      NoWeb#1:
        Enabled: true
    FastClimb:
      Enabled: true
      FastClimb#1:
        Enabled: true
    FastSneak:
      Enabled: true
      FastSneak#1:
        Enabled: true
    AntiRotate:
      Enabled: true
      AntiRotate#1:
        Enabled: true
  Render:
    Enabled: true
    AutoSneak:
      Enabled: true
      AutoSneak#1:
        Enabled: true
    NoSwing:
      Enabled: true
      NoSwing#1:
        Enabled: true
    InvalidMovement:
      Enabled: true
      InvalidMovement#1:
        Enabled: true
    Spinbot:
      Enabled: true
      Spinbot#1:
        Enabled: true
    SkinBlinker:
      Enabled: true
      SkinBlinker#1:
        Enabled: true
  Combat:
    Enabled: true
    AntiKB:
      Enabled: true
      AntiKB#1:
        Enabled: true
    HighCPS:
      Enabled: true
      HighCPS#2:
        Enabled: true
      HighCPS#1:
        Enabled: true
      HighCPS#3:
        Enabled: true
    KillAura:
      Enabled: true
      KillAura#6:
        Enabled: true
      KillAura#5:
        Enabled: true
      KillAura#2:
        Enabled: true
      KillAura#7:
        Enabled: true
    FastBow:
      Enabled: true
      FastBow#1:
        Enabled: true
    AutoArmor:
      Enabled: true
      AutoArmor#1:
        Enabled: true
    AutoClicker:
      Enabled: true
      AutoClicker#1:
        Enabled: true
  World:
    Enabled: true
    Scaffold:
      Enabled: true
      Scaffold#2:
        Enabled: true
      Scaffold#3:
        Enabled: true
      Scaffold#1:
        Enabled: true
    AutoBuild:
      Enabled: true
      AutoBuild#1:
        Enabled: true
    FastBreak:
      Enabled: true
      FastBreak#1:
        Enabled: true
    IllegalBlockPlace:
      Enabled: true
      IllegalBlockPlace#1:
        Enabled: true
    IllegalBlockBreak:
      Enabled: true
      IllegalBlockBreak#1:
        Enabled: true
  Player:
    Enabled: true
    AutoTool:
      Enabled: true
      AutoTool#1:
        Enabled: true
    GhostHand:
      Enabled: true
      GhostHand#2:
        Enabled: true
    SafeWalk:
      Enabled: true
      SafeWalk#1:
        Enabled: true
    NoFall:
      Enabled: true
      NoFall#1:
        Enabled: true
    ChestStealer:
      Enabled: true
      ChestStealer#1:
        Enabled: true
    AntiFire:
      Enabled: true
      AntiFire#1:
        Enabled: true
    SelfHarm:
      Enabled: true
      SelfHarm#1:
        Enabled: true
    Zoot:
      Enabled: true
      Zoot#1:
        Enabled: true
    FastEat:
      Enabled: true
      FastEat#1:
        Enabled: true
  Tick:
    Enabled: true
    Blink:
      Enabled: true
      Blink#1:
        Enabled: true
    Timer:
      Enabled: true
      Timer#1:
        Enabled: true
