# ----------------------------------------------------------
#
#               NOPE Anti-Cheat Configuration
#
#   This is the configuration for NOPE. I recommend keeping
#    the default values unless you know what you're doing.
#
# ----------------------------------------------------------
ConfigVersion: 1.4
#               -------------------------------
#                     Global Configuration
#               -------------------------------

Global: true # If disabled, NOPE will be disabled

# NONE, file, or hastebin
# hastebin will not work if dev mode is enabled to prevent abuse
# hastebin will log the link to the log within the file
Log: file # NONE, file, or hastebin

UpdateChecker:
  Enabled: true
  InGame: true
BungeeNameOverride: '' # If not empty this will override the server name

#               -------------------------------
#                     Banwave Configuration
#               -------------------------------

BanwaveRate: 36000 # Rate of banwave (in ticks) -1 to disable

#               -------------------------------
#                  Notification Configuration
#       Make sure staff members have nope.message.normal
#               -------------------------------

Minimum: 40 #Minimum VL to notify staff members
SecondsMinimum: 10000 #Cooldown of hack messages to prevent spam

# Each new color is a new level, this is based off percentage to VL for instant ban
# More colors = more notifications
VlColors: 
- '&a'
- '&6'
- '&4'

# If enabled, developer messages will be sent to the player and commands will not execute
DevMode: false 
DebugMode: false

#               -------------------------------
#                  Action Configuration
# Actions:
# kick:Reason        Kick the player for the specified reason
# ban:Time:Reason    Ban the player for the specified time/reason
# banwave:Time:Reason            Add the player to the banwave
# cancel             Teleport the player back
# pmsg:[Message]     Send a message to the player
# msg:[all/Permission]:[Message] Can also specify all
# cmd:[Command]      Run a command as the player
# ccmd:[Command]     Run a command from console
# log:type:message   Logs the message either to FILE, INGAME, or CONSOLE (perm: nope.message.normal)
#
# Conditions: (<, <=, =, !=, >=, >=)
# If a condition is not fullfilled, none of the following actinos will be run
# The ones with > you can replace with the appropriate operator
#
# vl>[Amo]           Will run actions if the VL matches the threshold
# tps>[Amo]          Will run actions if the server's TPS matches the threshold
# ping>[Amo]         Will run actions if the player's ping matches (NOT RECOMMENDED) players can spoof their ping
# delay:[Delay]      Wait X milliseconds before executing the NEXT action
# notdev             Will not run the next actions if the in dev mode
# rnd:.40            Will run the actions 40% of the time
# 
# Placeholders:

# %player% - The name of the player that was banned
# %hack% - What hack the player was banned for
# %debug% - The debug ID of the check
# %vl% - The VL of the hack that the player was at when they were banned
# %world% - What world the player was in when they were banned, this may be null if they were offline
# %token% - The ban token (only for ban)
#
# PAPI is also supported
#               -------------------------------
Actions:
  FastBreak:
  - 'basiclog|cancel|vl>400|lagkick|flog|log:FILE:Kicked %player% for %check%|vl>600|cban'
  FastClimb:
  - 'basiclog|vl>50|delay:500|cancel|vl>200|cancel|vl>400|ikick|vl>600|cban'
  Blink:
  - 'basiclog|vl>200|delay:2000|cancel|tps>15|vl>250|lagkick|vl>500|cancel|flog|cban'
  KillAura:
  - 'basiclog|vl>400|flog|vl>600|cban'
  Speed:
  - 'basiclog|rndcancel|vl>100|cancel|vl>800|addbanwave|vl>1200|cban|logban'
  Default:
  - 'basiclog|vl>20|cancel|vl>100|flog|tps>10|vl>400|ikick|vl>800|addbanwave|vl>1200|cban|logban'

# Commands are loaded and created in order. Define a custom command first before using it in another custom command.
Commands:
  flog: 'log:FILE:%player% failed %debug% (%vl%)|delay:5000|log:CONSOLE:%player% failed %debug%'
  alog: 'vl>20|vl<200|delay:10000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed a &a%check%&7 check. (VL: &e%vl%&7)'
  elog: 'vl>200|vl<400|delay:10000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed a &e%check%&7 check. (VL: &e%vl%&7)'
  clog: 'vl>400|vl<600|delay:10000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed a &c%check%&7 check. (VL: &e%vl%&7)'
  4log: 'vl>600|delay:500|flog|delay:10000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed a &4%check%&7 check. (VL: &e%vl%&7)'
  basiclog: 'alog|elog|clog|4log'
  logban: 'log:INGAME:&4&l[&c&lNOPE&4&l] &c%player% &7was banned for &b%check%&7.|log:FILE:Banned %player% for %debug% %vl%'
  ikick: 'delay:60000|kick:Irregular Gameplay'
  lagkick: 'ping>150|kick:Extreme Ping'
  rndcancel: 'rnd:.80|cancel'
  cban: "notdev|ban:2628000000:&4NOPE Anti-Cheat&r\n&7Token: &e%token%"
  addbanwave: "notdev|banwave:2628000000:&4NOPE Anti-Cheat&r\n&7Token: &e%token%"

#               -------------------------------
#                     Check Configuration
#       Here you can configure which checks are/aren't enabled
#         You can also toggle these ingame with /nope stats
#   make sure to restart your server after modifying these settings
#               -------------------------------

Checks:
  Combat:
    Enabled: true
    KillAura:
      Enabled: true
      KillAura#3:
        Enabled: true
      KillAura#4:
        Enabled: true
      KillAura#1:
        Enabled: true
      KillAura#2:
        Enabled: true
    AutoClicker:
      Enabled: true
      AutoClicker#1:
        Enabled: true
    HighCPS:
      Enabled: true
      HighCPS#3:
        Enabled: true
      HighCPS#2:
        Enabled: true
      HighCPS#1:
        Enabled: true
    AutoArmor:
      Enabled: true
      AutoArmor#1:
        Enabled: true
    FastBow:
      Enabled: true
      FastBow#1:
        Enabled: true
    AntiKB:
      Enabled: true
      AntiKB#1:
        Enabled: true
  Movement:
    Enabled: true
    Spider:
      Enabled: true
      Spider#1:
        Enabled: true
    Speed:
      Enabled: true
      Speed#2:
        Enabled: true
      Speed#4:
        Enabled: true
      Speed#3:
        Enabled: true
      Speed#1:
        Enabled: true
    BHop:
      Enabled: true
      BHop#1:
        Enabled: true
    GlobalSprint:
      Enabled: true
      GlobalSprint#1:
        Enabled: true
    Flight:
      Enabled: true
      Flight#5:
        Enabled: true
      Flight#2:
        Enabled: true
      Flight#4:
        Enabled: true
      Flight#1:
        Enabled: true
      Flight#3:
        Enabled: true
      Flight#6:
        Enabled: true
    AntiRotate:
      Enabled: true
      AntiRotate#1:
        Enabled: true
    FastSneak:
      Enabled: true
      FastSneak#1:
        Enabled: true
    ClonedMovements:
      Enabled: true
      ClonedMovement#1:
        Enabled: true
    Jesus:
      Enabled: true
      Jesus#2:
        Enabled: true
      Jesus#3:
        Enabled: true
      Jesus#1:
        Enabled: true
      Jesus#4:
        Enabled: true
    NoSlowDown:
      Enabled: true
      NoSlowDown#4:
        Enabled: true
      NoSlowDown#5:
        Enabled: true
      NoSlowDown#1:
        Enabled: true
      NoSlowDown#2:
        Enabled: true
      NoSlowDown#3:
        Enabled: true
    FastClimb:
      Enabled: true
      FastClimb#1:
        Enabled: true
    AntiAFK:
      Enabled: true
      AntiAFK#1:
        Enabled: true
    NoWeb:
      Enabled: true
      NoWeb#1:
        Enabled: true
    Glide:
      Enabled: true
      Glide#1:
        Enabled: true
    InventoryMove:
      Enabled: true
      InventoryMove#1:
        Enabled: true
    AutoWalk:
      Enabled: true
      AutoWalk#1:
        Enabled: true
  Render:
    Enabled: true
    Spinbot:
      Enabled: true
      Spinbot#1:
        Enabled: true
    AutoSneak:
      Enabled: true
      AutoSneak#1:
        Enabled: true
    InvalidMovement:
      Enabled: true
      InvalidMovement#1:
        Enabled: true
    SkinBlinker:
      Enabled: true
      SkinBlinker#1:
        Enabled: true
    NoSwing:
      Enabled: true
      NoSwing#1:
        Enabled: true
  Player:
    Enabled: true
    SelfHarm:
      Enabled: true
      SelfHarm#1:
        Enabled: true
    AutoTool:
      Enabled: true
      AutoTool#1:
        Enabled: true
    ChestStealer:
      Enabled: true
      ChestStealer#1:
        Enabled: true
    GhostHand:
      Enabled: true
      GhostHand#2:
        Enabled: true
    Zoot:
      Enabled: true
      Zoot#1:
        Enabled: true
    SafeWalk:
      Enabled: true
      SafeWalk#1:
        Enabled: true
    NoFall:
      Enabled: true
      NoFall#1:
        Enabled: true
    AntiFire:
      Enabled: true
      AntiFire#1:
        Enabled: true
    FastEat:
      Enabled: true
      FastEat#1:
        Enabled: true
  World:
    Enabled: true
    Scaffold:
      Enabled: true
      Scaffold#2:
        Enabled: true
      Scaffold#3:
        Enabled: true
      Scaffold#1:
        Enabled: true
    IllegalBlockPlace:
      Enabled: true
      IllegalBlockPlace#1:
        Enabled: true
    IllegalBlockBreak:
      Enabled: true
      IllegalBlockBreak#1:
        Enabled: true
    AutoBuild:
      Enabled: true
      AutoBuild#1:
        Enabled: true
    FastBreak:
      Enabled: true
      FastBreak#1:
        Enabled: true
  Tick:
    Enabled: true
    Blink:
      Enabled: true
      Blink#1:
        Enabled: true
    Timer:
      Enabled: true
      Timer#1:
        Enabled: true