name: NOPE
main: org.mswsplex.anticheat.msws.NOPE
version: 1.2.3
description: 1.15.2 Minecraft Anticheat
api-version: 1.15
author: MSWS
commands:
  nope:
    usage: /<command>
    aliases:
    - ac
    - anticheat