name: NOPE
main: xyz.msws.anticheat.NOPE
version: 1.3
description: 1.15.2 Minecraft Anticheat
api-version: 1.15
author: MSWS
softdepend:
- ProtocolLib
commands:
  nope:
    usage: /<command>
    aliases:
    - ac
    - anticheat