name: NOPE
main: org.mswsplex.anticheat.msws.NOPE
version: 1.2.9
description: 1.15.2 Minecraft Anticheat
api-version: 1.15
author: MSWS
softdepend:
- ProtocolLib
commands:
  nope:
    usage: /<command>
    aliases:
    - ac
    - anticheat