name: NOPE
main: xyz.msws.anticheat.NOPE
version: 1.4.5
description: 1.15.2 Minecraft Anticheat
api-version: 1.15
author: MSWS
softdepend:
- ProtocolLib
- MaxBans
- AdvancedBan
- LapisBans
- LiteBans
- BanManagement
- PlaceholderAPI
- mcMMO
- CrazyEnchantments
commands:
  nope:
    usage: /<command>
    aliases:
    - ac
    - anticheat